baseURL = "http://www.planning-assistance.com"
languageCode = "en-GB"
paginate = 6
theme = "portio"
title = "Planning Assistance"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Services"
url = "#service"
weight = 2
[[menu.main]]
name = "About"
url = "#about"
weight = 3
[[menu.main]]
name = "Expertise"
url = "#resume"
weight = 4
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 5
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Huntshaw Mains, Earlston, Berwickshire, TD4 6AF"
email = "youngercora@gmail.com"
openingHours = "Open from 9am to 5pm (closed weekends)"
phone = "+(448) 833 5272 332"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 3
